name: Deploy to Azure Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C57EB55ED4084527A64A74A7137C8AC1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_518D743781544F3FA466D9EF4BE82CCD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21756AB212C34ABAAD132D625835FA40 }}

      - name: Build and deploy
        run: |
          az acr build --registry expenseregistryy --image expense-api:${{ github.sha }} ./expense-backend
          az containerapp update --name expense-api-2025 --resource-group expense-app-rg --image expenseregistryy.azurecr.io/expense-api:${{ github.sha }}
